PreCommit:
  # Style Check
  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop', '-c', './.rubocop.yml']
    on_warn: fail

  # Security Check
  Brakeman:
    enabled: true
    command: ['bundle', 'exec', 'brakeman']
    on_warn: fail

  # Style Check in HAML
  HamlLint:
    enabled: true
    command: ['bundle', 'exec', 'haml-lint', 'app/views/']
    on_warn: fail

  # YAML Check
  YamlSyntax:
    enabled: true
    on_warn: fail

  # Dependency Check
  BundleCheck:
    enabled: true
    on_warn: fail

  # Migration Check
  RailsSchemaUpToDate:
    enabled: true
    on_warn: fail

  # Checks for hard tabs in files
  HardTabs:
    enabled: true
    on_warn: fail